### ISSUE TITLE
Code review for redesign (v1.x prerelease)

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-tabs#10]
Hey @randyaskin. This is a code review for px-tabs as of fa0e4ac618f6f8985a5daf6fe84db55fbceb3643. Doing on an issue since there's no pull request and this lets Github track changes for us.

Below comments are suggestions, your input/questions/differences of opinion are strongly welcomed. I'm just someone on the outside looking in. 😄 

-------------------------------

* [x] **Switch increment/decrement methods to use native iron-selector methods**

Targeting this bit of code: https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L109-L137

```
      /**
       * Move forward by one tab, with wraparound from last to first.
       */
      _increment: function(evt) {
        evt.detail.keyboardEvent.preventDefault();
        // if last tab is selected, wrap around
        if(this.selected === this._tabCount - 1) {
          this.selected = 0;
        }
        // else move forward one tab
        else {
          this.selected++;
        }
      },
      /**
       * Move backward by one tab, with wraparound from first to last.
       */
      _decrement: function(evt) {
        evt.detail.keyboardEvent.preventDefault();
        // if first tab is selected, wrap around
        if(this.selected === 0 || this.selected === '0') {
          this.selected = this._tabCount - 1;
        }
        // else move back one tab
        else {
          this.selected--;
        }
      },
```

This works fine if `selected` is a number. But iron-selector allows `selected` to be a string if `attr-for-selected` is used. Here's an example:

```
    <px-tab-set selected="{{selected}}" attr-for-selected="name">
      <px-tab name="george">George's Tab</px-tab>
      <px-tab name="sally">Sally's Tab</px-tab>
      <px-tab name="maria">Maria's Tab</px-tab>
    </px-tab-set>
```

If you click to select the first tab, the `selected` attribute will now be `george`. But if you use the keyboard to move right, you'll get this error thrown:

```
px-tab-set.html:223 Uncaught TypeError: Cannot read property 'id' of null
    at HTMLElement._tabChanged (px-tab-set.html:223)
    at HTMLElement.<anonymous> (px-tab-set.html:180)
    at Debouncer.complete (polymer-mini.html:2175)
    at Debouncer.boundComplete (polymer-mini.html:2152)
```

The methods expect `selected` to be a number that can be added to/subtracted from, so doing math on `selected` as a string fails here. Thankfully the iron-selector behavior has a method that can do this for us if selected is a string or number. It'll handle the wrapping back from the end to the beginning as well:

```
      _increment: function(evt) {
        evt.detail.keyboardEvent.preventDefault();
        this.selectNext();
      },

      _decrement: function(evt) {
        evt.detail.keyboardEvent.preventDefault();
        this.selectPrevious();
      },
```

-------------------------------

* [x] **Remove all the code that tracks tab count**

If we make the change above, we don't need to track the tab count anymore. We can kill a bunch of code:

1. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L88-L91
2. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L100-L103
3. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L139-L147

-------------------------------

* [x] **Stop reaching into `px-tab` shadow root from `px-tab-set`**

This bit of code in `px-tab-set` finds the active `px-tab` HTML element in the light DOM and reaches into its shadow root to set the `tab-title--selected` class:

https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L184-L210

```
      _changeTabStyle: function(tab, selectedStyle) {
        var constructedClass = "tab-title";
        //check if configured with bare styles
        if (tab) {
          var constructedClassMod =  constructedClass + '--selected';
          var cl = tab.$.tabtitle.classList;
          if (selectedStyle && !cl.contains(constructedClassMod)) {
            cl.add(constructedClassMod);
            tab.setAttribute('aria-selected','true');
          }
          else if (!selectedStyle && cl.contains(constructedClassMod)) {
            cl.remove(constructedClassMod);
            tab.setAttribute('aria-selected','false');
          }
        }
      },
```

It would be cool if we could avoid doing this, because it creates a strong link between `px-tab-set` and `px-tab` — when the internals of one change, the other will have to change too.

iron-selector is also our friend here. It sets the `iron-selected` class on the selected element, in this case whichever `px-tab` element is selected. In the Sass styles for `px-tab`, we can look for a class on our host instead of a class on our title to give the title a selected style.

We can remove this code https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/sass/px-tab.scss#L46-L50:

```
  &--selected {
    color: var(--px-tab-color--selected, black);
    border-bottom: 2px solid var(--px-tab-color--selected, black);
    font-weight: bold;
  }
```

And move it to a new class below `.tab-title` scoped with `host-context`:

```
:host-context(.iron-selected) .tab-title {
    color: var(--px-tab-color--selected, black);
    border-bottom: 2px solid var(--px-tab-color--selected, black);
    font-weight: bold;
}
```

-------------------------------

* [x] **Remove all the code that handles selecting/deselecting, since iron-selector does that for us now**

This should let us take out all this code from `px-tab-set`, since iron-selector is doing it for us:

1. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L74-L78
2. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L96-L97
3. https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L161-L224

The only thing I'm not sure about here is https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L158:

```
      _onResize: function() {
        this.debounce('_onResize', function() {
          this._scroll();
          this._tabChanged(this.selectedItem);
        }, 10);
      },
```

It looks like we call `tabChanged` on resize. Not sure why, but maybe there's a case I don't get. If so, we might need to do something different to force iron-selector to re-mark the selected item with the `.iron-selected` class, since we removed the method we used before to apply classes.

--------------------------

* [x] **Style suggestion: move behaviors to the top**

We usually put the behaviors array right under the `is` in the polymer constructor, so its clear what this element is mixing into itself to define its functionality. Maybe we could move this block up? https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab-set.html#L226-L228

---------------------------

* [x] **Remove unneeded id in px-tab**

We don't need to use `id="tabtitle"` in JS anymore so we can delete it: https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab.html#L43

---------------------------

* [x] **Kill empty properties block in px-tab**

https://github.com/PredixDev/px-tabs/blob/fa0e4ac618f6f8985a5daf6fe84db55fbceb3643/px-tab.html#L54-L56

---------------------------

* [x] **Deprecate px-tab-pages in favor of iron-pages**

Chatted to martin about this and he 👍 it. Seems like we can just delete `px-tab-pages.html` and change our docs to recommend using `iron-pages` instead. `px-tab-pages` seems to have a 1:1 API and feature parity with iron-pages. Switching over means one less thing for us to support. Woot woot. Will require some associated doc changes to show usage with iron-pages instead — should just mean finding all references to px-tab-set in our docs and replace with iron-pages, keeping the bound attributes the same.
